### ISSUE TITLE
Make this UI-extension one-click installable

### ISSUE THREAD

**Issue by stefanjudis** [tremby/contentful-multitext#1]
Hey Bart,

this looks awesome! Let me introduce myself – I'm Stefan and I work in the Contentful DevRel team. 

For a few months now, you can install UI-extension with on click in the interface. The only requirement is to make the assets available in the repo itself. Would you be up for that?

(I know checking in generate files a little bad...)

Would you be up for that?

![one-click](https://user-images.githubusercontent.com/962099/46302882-a2213e80-c5aa-11e8-950c-51d9ecb66c0c.gif)

**Comment by tremby** [comment]
Hm. If you guys made it so you could one-click install from *NPM* that would be nicer, since I could have a prepublish script which does the build, the built files would publish to NPM, and I wouldn't have to have generated files in the repo.

Would you be up for *that*?... ;)

**Comment by tremby** [comment]
Or allow one-click publish from other arbitrary sources, since I'd be fine with uploading a built package of this to a public S3 bucket or something.

As you can tell, I'm not so keen on checking in built files. Makes me feel gross. Even the package.lock file kinda does.

**Comment by stefanjudis** [comment]
I feel ya. :)

For now npm is not an option... Alternatively an s3 bucket would work though, it think. :) 

You could tweak the extension descriptor like so.:)

https://github.com/contentful/extensions#3rd-party-hosted

**Comment by tremby** [comment]
Oh and then the "install from Github" would work? If so, maybe I'll do that.

**Comment by stefanjudis** [comment]
Haven't tried it but yeah... If it works and you publish to npm you could even point to unpgk as it's mirrowing npm.

**Comment by tremby** [comment]
Ah, that'd beat having to set up a bucket. I'll try that first.

**Comment by tremby** [comment]
It works! Thanks for the guidance.

**Comment by tremby** [comment]
@stefanjudis, I question you guys accepting only Github URLs. Why is that? I can't see it adding any security, given that you only grab the `extension.json` file from there and allow that to point anywhere on the web. So why not just take that one step further and allow pointing to an `extension.json` file anywhere, which can then have relative URLs for the extension main HTML file etc? Why tie people to Github, when they might prefer Gitlab or Bitbucket or something self-hosted?
